# Usar una imagen base oficial de Python
FROM python:3.8-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /usr/src/app

# Copiar el archivo de dependencias y luego instalar esas dependencias
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del código de la aplicación en el contenedor
COPY . .

# Indicar que el contenedor escucha en el puerto 5000
EXPOSE 5000

# Comando para ejecutar la aplicación
CMD ["python", "./app.py"]