"""add title a answers_json to document

Revision ID: a34d068b9bdd
Revises: 18d969ad0345
Create Date: 2024-01-07 10:55:55.176485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34d068b9bdd'
down_revision = '18d969ad0345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('answers_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('answers_json')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
