"""Add column for document in table resulting_document and user id as foreign key

Revision ID: e3113d8023d3
Revises: 04076bc4b57f
Create Date: 2024-01-14 12:45:39.251885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3113d8023d3'
down_revision = '04076bc4b57f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resulting__document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_resulting_document_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resulting__document', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('document')

    # ### end Alembic commands ###
