"""rm title an answers_json to document and create new table called Resulting_Document

Revision ID: e7195dda12d9
Revises: a34d068b9bdd
Create Date: 2024-01-07 14:15:28.738662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7195dda12d9'
down_revision = 'a34d068b9bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resulting__document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('answers_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('answers_json')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('answers_json', sa.TEXT(), nullable=True))

    op.drop_table('resulting__document')
    # ### end Alembic commands ###
